### ISSUE TITLE
If double jump is available, player can take single jump then another turn

### ISSUE THREAD

**Issue by justingolden21** [codethejason/checkers#1]
It's in the title. A player with an available double jump can take one jump then instead of taking the next jump they can move elsewhere. Also despite forced jump not being used, you can't end the turn after a single jump if double is available.

**Comment by codethejason** [comment]
Good catch, and yeah maybe having some time of validation to prevent a player from deselecting the piece that single jumped (but can double jump) would fix the issue. Would you like to work on it @justingolden21?

**Comment by justingolden21** [comment]
The way I'd handle it, assuming that they're not allowed to single jump if a double jump is available, is to check after the jump if another jump is available and if so set a global variable that tracks the piece that just jumped and must jump again. At the start of the function that checks if a move is valid then if that piece exists then it must be the piece to jump, and after that if statement you set the global back to null or undefined.

**Comment by justingolden21** [comment]
One other thing: I don't know if you just added this or it's been like this, but if a jump is available you don't have to take it, but you can't move a piece that could jump in a way that's not a jump. That's how you have it written, which doesn't coincide with either forced jump rules or non-forced jump rules.

**Comment by justingolden21** [comment]
Also if piece 1 jumps once and has another jump, then piece 2 jumps once and has another jump, piece 2 can't jump again and the player who controls pieces 1 and 2 has their turn over. In other words the issue occurs at most once.

**Comment by codethejason** [comment]
Yeah, maybe a checking algorithm to check jumping moves for all the pieces instead of just the selected one. For your second comment, do you mean how that's supposed to be in checkers rules? I cannot replicate the issue on the demo and I don't remember that being a checkers rule.
