### ISSUE TITLE
Problem with rules in the Netherlands

### ISSUE THREAD

**Issue by PKHG** [codethejason/checkers#7]
Hallo,
my rules say a stone must capture a stone even backward,  did not see it .
Next rule the longest capture has to be used.
Could not see it in the javascript. not so easy problem to solve programmatically,

I had  the possibility with of this rules programmed in python for GIMP.
I should have a backup somewhere on a external harddrive ... will look for it  ;0P

Would like to get a reply ;-)

Greets
     Peter K.H. Gragert (a grandpa ;-) )

**Comment by codethejason** [comment]
Feel free to fork and modify the code! The rules here are based on standard US rules.

**Comment by PKHG** [comment]
Us rules, Jason,
Are not used in the Netherlands ...
Busy to revive my checkers bord in Gimp. worked years ago very nice,
now on the way, takes some time because Gimp is upgraded  and gives
 me some problems now.
If it works again and you are interested you can get my code. (Python0
The biggest problem:  find out the (maybe several) longest capture series
of a king.
Greets
     Peter

Op ma 9 nov. 2020 om 02:30 schreef Jason Wong <notifications@github.com>:
